template-file-path: infrastructure.yaml
parameters:
  PrivateSubnet1Cidr: 10.0.2.0/24
  PublicSubnet1Cidr: 10.0.1.0/24
  VpcCidr: 10.0.0.0/16
  WebServerPort: '80'
  InstanceType: t3.micro
  AmiId: /aws/service/ami-amazon-linux-latest/amzn2-ami-hvm-x86_64-gp2
tags: {}
